apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-cm
spec:
  inputs:
    resources:
      - name: tekton1-git
        type: git
    params:
      - name: pathToContext
        type: string
        default: /workspace/tekton1-git
      - name: targetNamespace
        type: string
        default: tekton-lab
  steps:
    - name: oc-service
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - oc apply -f /workspace/tekton1-git/tekton-pipeline/deployment.yaml --token=$REG_PWD -n tekton-lab
