---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: buildah
spec:
  inputs:
    params:
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image.
      default: quay.io/buildah/stable:v1.11.0
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS registry)
      default: "false"
    resources:
    - name: tekton1-git
      type: git
  outputs:
    resources:
    - name: tekton1-image
      type: image
  steps:
  - name: build
    image: quay.io/buildah/stable:v1.11.0
    workingDir: /workspace/tekton1-git
    command: ['buildah', 'bud', '--tls-verify=false', '--format=docker', '-f', './Dockerfile', '-t', 'image-registry.openshift-image-registry.svc:5000/tekton-lab/tekton1:latest', '.']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  - name: push
    image: quay.io/buildah/stable:v1.11.0
    workingDir: /workspace/tekton1-git
    command: ['buildah', 'push', '--tls-verify=false', 'image-registry.openshift-image-registry.svc:5000/tekton-lab/tekton1:latest', 'image-registry.openshift-image-registry.svc:5000/tekton-lab/tekton1:latest']
    volumeMounts:
    - name: varlibcontainers
      mountPath: /var/lib/containers
    securityContext:
      privileged: true
  volumes:
  - name: varlibcontainers
    emptyDir: {}
